// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCixY3ldoEkhjURx1YrQ65R2-2ilyeVI6Q',
    appId: '1:315288299970:web:6aa5720e86d0fb1511ce5b',
    messagingSenderId: '315288299970',
    projectId: 'it-inventory-8e690',
    authDomain: 'it-inventory-8e690.firebaseapp.com',
    storageBucket: 'it-inventory-8e690.firebasestorage.app',
    measurementId: 'G-Z1MS20L4T2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNNbX4wNesCJLhbWr4InNc9MwShHXuR88',
    appId: '1:315288299970:android:f61bff62f4f7418711ce5b',
    messagingSenderId: '315288299970',
    projectId: 'it-inventory-8e690',
    storageBucket: 'it-inventory-8e690.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbp5zl55NFpVuPm9uPu4aZtdQe8zFjHjo',
    appId: '1:315288299970:ios:6e2f76846735cc4d11ce5b',
    messagingSenderId: '315288299970',
    projectId: 'it-inventory-8e690',
    storageBucket: 'it-inventory-8e690.firebasestorage.app',
    iosBundleId: 'com.example.itManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbp5zl55NFpVuPm9uPu4aZtdQe8zFjHjo',
    appId: '1:315288299970:ios:6e2f76846735cc4d11ce5b',
    messagingSenderId: '315288299970',
    projectId: 'it-inventory-8e690',
    storageBucket: 'it-inventory-8e690.firebasestorage.app',
    iosBundleId: 'com.example.itManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCixY3ldoEkhjURx1YrQ65R2-2ilyeVI6Q',
    appId: '1:315288299970:web:479bfd19acc050e811ce5b',
    messagingSenderId: '315288299970',
    projectId: 'it-inventory-8e690',
    authDomain: 'it-inventory-8e690.firebaseapp.com',
    storageBucket: 'it-inventory-8e690.firebasestorage.app',
    measurementId: 'G-QNPVPL46X3',
  );
}
